trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetAuthenticate@1
  displayName: 'NuGet Authenticate'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.100'

- script: dotnet restore src/AdoNet.Fluent.SqlServer.sln
  displayName: 'Restore NuGet Packages'

- script: dotnet build src/AdoNet.Fluent.SqlServer.sln --configuration $(buildConfiguration) --no-restore
  displayName: 'Build Solution'

- script: dotnet pack src/AdoNet.Fluent.SqlServer/AdoNet.Fluent.SqlServer.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack Project'

- script: dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --api-key $(System.AccessToken) --source https://pkgs.dev.azure.com/marcoshidalgonunes/AdoNet/_packaging/AdoNet/nuget/v3/index.json
  displayName: 'Push NuGet Package'